#Robot BIOLOID TIPO A
bioloid:
  nombre: Bioloid A
  tipo: Humanoide
  base: origen
  numerodecadenas: 4
  cadenas:
    brazoderecho:
      nombre: Brazo Derecho
      gdl: 3
      limites:
        - -150
        - 150
        - -100
        - 90
        - -100
        - 100
      params:
        cantidad: 10
        posiciontheta:
        - 3
        - 6
        - 9
        offset:
          - 0
          - 90
          - 0
          - -90
          - 0
          - 0
          - -90
          - 90
          - 0
          - 90
        d:
          - 0
          - 0
          - 0
          - 25
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        a:
          - -47
          - 0
          - 0
          - 14.5
          - 0
          - 0
          - 67.5
          - 0
          - 0
          - -74.5
        alpha:
          - 0
          - -90
          - 0
          - 0
          - -90
          - 0
          - 0
          - 0
          - 0
          - 90

    brazoizquierdo:
      nombre: Brazo Izquierdo
      gdl: 3
      limites:
        - -150
        - 150
        - -90
        - 100
        - -100
        - 100
      params:
        cantidad: 10
        posiciontheta:
          - 3
          - 6
          - 9
        offset:
          - 0
          - 90
          - 0
          - 90
          - -180
          - 0
          - -90
          - 90
          - 0
          - -90
        d:
          - 0
          - 0
          - 0
          - 25
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        a:
          - 47
          - 0
          - 0
          - 14.5
          - 0
          - 0
          - 67.5
          - 0
          - 0
          - 74.5
        alpha:
          - 0
          - 90
          - 0
          - 0
          - -90
          - 0
          - 0
          - 0
          - 0
          - 90

    piernaderecha:
      nombre: Pierna Derecha
      gdl: 6
      limites:
        - -95
        - 10
        - -73
        - 50
        - -128
        - 23
        - -142
        - 0
        - -23
        - 49
        - -54
        - 74
      params:
        cantidad: 22
        posiciontheta:
          - 5
          - 7
          - 10
          - 14
          - 18
          - 21
        offset:
          - -90
          - 90
          - 180
          - -90
          - 0
          - 90
          - 0
          - -90
          - 90
          - 0
          - 0
          - 0
          - -90
          - 0
          - 0
          - 0
          - -90
          - 0
          - -90
          - 90
          - 0
          - 90
        d:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 37
          - 0
          - 0
          - 0
          - 0
          - 0
          - -75
          - 0
          - 0
          - 0
          - -14.5
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        a:
          - 89.5
          - 0
          - 38.5
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 14.5
          - 0
          - 0
          - 0
          - 75
          - 0
          - 0
          - 0
          - 0
          - 0
          - 29.5
        alpha:
          - 0
          - 0
          - -90
          - 0
          - 0
          - -90
          - 0
          - 90
          - 0
          - 0
          - -90
          - 90
          - 0
          - 0
          - -90
          - 90
          - 0
          - 0
          - 90
          - 0
          - 0
          - 0

    piernaizquierda:
      nombre: Pierna Izquierda
      gdl: 6
      limites:
        - -10
        - 95
        - -50
        - 73
        - -23
        - 128
        - 0
        - 142
        - -49
        - 23
        - -74
        - 54
      params:
        cantidad: 22
        posiciontheta:
          - 5
          - 7
          - 10
          - 14
          - 18
          - 21
        offset:
          - -90
          - 90
          - 0
          - -90
          - 0
          - -90
          - 0
          - -90
          - 90
          - 0
          - 0
          - 0
          - 90
          - 0
          - 0
          - 0
          - 90
          - 0
          - 90
          - -90
          - 0
          - 90
        d:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 37
          - 0
          - 0
          - 0
          - 0
          - 0
          - -75
          - 0
          - 0
          - 0
          - -14.5
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        a:
          - 89.5
          - 0
          - 38.5
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - -14.5
          - 0
          - 0
          - 0
          - -75
          - 0
          - 0
          - 0
          - 0
          - 0
          - 29.5
        alpha:
          - 0
          - 0
          - 90
          - 0
          - 0
          - -90
          - 0
          - -90
          - 0
          - 0
          - -90
          - 90
          - 0
          - 0
          - -90
          - 90
          - 0
          - 0
          - 90
          - 0
          - 0
          - 0